server:
  port:9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/users/**
        - id: TRANSACTIONS-SERVICE
          uri: lb://TRANSACTIONS-SERVICE
          predicates:
          - Path=/transactions/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost