server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedHeaders:
              - content-type
              allowedMethods: "*"
              allowed-origin-patterns: "*"
              allowCredentials: true
      routes:
        - id: REGISTER-SERVICE
          uri: lb://REGISTER-SERVICE
          predicates:
          - Path=/users/**
        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
          - Path=/transactions/**
       
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost