server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: REGISTER-SERVICE
          uri: lb://REGISTER-SERVICE
          predicates:
          - Path=/users/**
        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
          - Path=/transactions/**
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:3000"
              allowedMethods: 
              - POST
              - GET
       
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost